language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  pip install -r requirements.txt

script:
  # Test the package compilation and installation
  - pytest
  - python setup.py install

notifications:
  email:
    recipients:
      - leia@ssi.gouv.fr
    on_success: never
    on_failure: always
    on_pull_requests: always

